[reggen] skipto error fix
Previous fix #654 wasn't correct.

Problem:

    `skipto` field value should be string as shown in example, not
    integer. But `rv_plic.hjson.tpl` set it to integer type. It results
    in to wrap the value with `hex()` to make it string type.

    This make the rv_plic reports correct error but it let build_docs.py
    failed.

```
Traceback (most recent call last):
  File "./util/build_docs.py", line 165, in <module>
    main()
  File "./util/build_docs.py", line 151, in main
    process_all_files()
  File "./util/build_docs.py", line 127, in process_all_files
...
  File "/mistletoe/base_renderer.py", line 95, in render
    return self.render_map[token.__class__.__name__](token)
  File "util/docgen/lowrisc_renderer.py", line 301, in render_lowrisc_escape
    if validate.validate(obj) == 0:
  File "util/reggen/validate.py", line 1363, in validate
    " which is not a multiple of the register size " +
TypeError: 'str' object cannot be interpreted as an integer
```

Resolution:

    Rolled-back the `validate.py` error report code. And changed
    `rv_plic.hjson.tpl` to make `skipto` to string type.

Issue reported by @asb