[dv] Downgrade error when building vcs simv with newer compiler builds
Newer compiler versions have escalated this warning into an error by default, and
VCS generates code to build the simulation executable which fails this check.
De-escalate the error (only when building the simv itself.)
> rmapats.c:20:9: error: implicit declaration of function 'vcs_simpSetEBlkEvtID'
>  [-Wimplicit-function-declaration]

Signed-off-by: Harry Callahan <hcallahan@lowrisc.org>
(cherry picked from commit 22df9125eb2fadab6cb59fa1059a159aa026bd3d)