[reggen] Fix TypeError
Running reggen (e.g. through `make -C hw`) on the `v1-bronze` branch
fails with the following error message:

```
Traceback (most recent call last):
  File "/home/philipp/src/opentitan/util/topgen.py", line 964, in <module>
    main()
  File "/home/philipp/src/opentitan/util/topgen.py", line 860, in main
    generate_top_ral(completecfg, ip_objs, out_path)
  File "/home/philipp/src/opentitan/util/topgen.py", line 655, in generate_top_ral
    top_block.blocks.sort(key=lambda block: block.base_addr)
TypeError: '<' not supported between instances of 'int' and 'str'
```

Fix that by converting `base_addr` to str/int as necessary in all places
where it is used.

Signed-off-by: Philipp Wagner <phw@lowrisc.org>