Fix OT_DISABLE_HARDENING -Werror,-Wundef error
In file included from lib/crypto/crypto_ipc.c:10:
In file included from external/lowrisc_opentitan+/sw/device/lib/crypto/include/ecc_p256.h:8:
In file included from external/lowrisc_opentitan+/sw/device/lib/crypto/include/datatypes.h:12:
external/lowrisc_opentitan+/sw/device/lib/base/hardened.h:244:37: error: 'OT_DISABLE_HARDENING' is not defined, evaluates to 0 [-Werror,-Wundef]

Signed-off-by: Kor Nielsen <kor@google.com>
(cherry picked from commit 0dfcda19ca8ba516febbf263407e58d3e89a37bf)