[bazel] Add --config=asan and --config=ubsan
These new config flags are intended to be applied to cc_test() targets
that run on the host machine. For example, the following runs a test
binary with ASan enabled:

  $ ./bazelisk.sh test --config=asan \
    //sw/device/lib/base:status_unittest

Caveat 1: ASan is not implemented for riscv32.

  $ ./bazelisk.sh build \
    --platforms=@bazel_embedded//platforms:opentitan_rv32imc \
    --config=asan //sw/device/lib/base:status
  ...
  clang-13: error: unsupported option '-fsanitize=address' for target 'riscv32-unknown-unknown-elf'
  ...

Caveat 2: UBSan is platform-independent, but the linker portion of
--config=ubsan (-fsanitize=undefined) will not be picked up by custom
linker scripts.

  * This works because :status does not have a custom linker script:
    $ ./bazelisk.sh build \
      --platforms=@bazel_embedded//platforms:opentitan_rv32imc \
      --config=ubsan //sw/device/lib/base:status

  * This fails with a linker error:
    $ ./bazelisk.sh test \
      --platforms=@bazel_embedded//platforms:opentitan_rv32imc \
      --config=ubsan //sw/device/lib/testing/test_rom:test_rom
    ...
    /proc/self/cwd/sw/device/silicon_creator/mask_rom/bootstrap.c:320: undefined reference to `__ubsan_handle_builtin_unreachable'
    ...

Issue #13754

Signed-off-by: Dan McArdle <dmcardle@google.com>