Fix cryptolib build regression with modern LLVM
When built with LLVM 23:

external/lowrisc_opentitan+/sw/device/lib/base/hardened.h:510:7: error: extension version number parsing not currently implemented
  510 |       ".option push;"
      |       ^
<inline asm>:1:30: note: instantiated into assembly here
    1 |         .option push;.option arch, +zbt0p93;cmov a0, a0, a1, a2;.option pop;
      |                                     ^
In file included from external/lowrisc_opentitan+/sw/device/lib/base/hardened.c:5:

Signed-off-by: Kor Nielsen <kor@google.com>