Fix missing bazel deps in reggen.
External users may need to use newer versions of rules_python than
opentitan's 1.2.0.

rules_python 1.8.5 and later enforce stricter dependency isolation in
Python rules. Under the newer version, Python targets must explicitly
declare all imported modules in their `deps` to ensure they are packaged
into the runfiles sandbox.

Without these fixes, running `regtool` fails with the following import error
due to missing sandbox files:

Traceback (most recent call last):
  ...
  File ".../util/regtool.py", line 14, in <module>
    from reggen import (
  File ".../util/reggen/gen_tock.py", line 21, in <module>
    from version_file import VersionInformation
ModuleNotFoundError: No module named 'version_file'

Signed-off-by: Kor Nielsen <kor@google.com>