[rv_plic/dif] Pass input data by value
The argument `complete_data` of the `dif_plic_irq_complete()` function
is used as value, not as out param as it is documented. Adjust the
documentation to reflect that, and pass the argument by value.

This was detected by compiling with GCC11, which a maybe-uninitialized
warning in the PLIC unit test code, which causes the compilation to fail.

```
c++ -Isw/device/lib/dif/5fb29ed@@dif_plic_unittest@exe  -I../sw/device/lib/dif -I/home/philipp/src/opentitan -I/home/philipp/src/opentitan/build-out -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Werror -std=c++14 -g -DHOST_BUILD -Wimplicit-fallthrough -Wswitch-default -Wno-error=unused-function -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -pthread -isystem../sw/vendor/google_googletest/googlemock -isystem../sw/vendor/google_googletest/googlemock/include -isystem../sw/vendor/google_googletest/googletest -isystem../sw/vendor/google_googletest/googletest/include -DMOCK_MMIO -MD -MQ 'sw/device/lib/dif/5fb29ed@@dif_plic_unittest@exe/dif_plic_unittest.cc.o' -MF 'sw/device/lib/dif/5fb29ed@@dif_plic_unittest@exe/dif_plic_unittest.cc.o.d' -o 'sw/device/lib/dif/5fb29ed@@dif_plic_unittest@exe/dif_plic_unittest.cc.o' -c ../sw/device/lib/dif/dif_plic_unittest.cc
In file included from ../sw/vendor/google_googletest/googletest/include/gtest/gtest.h:376,
                 from ../sw/device/lib/dif/dif_plic_unittest.cc:9:
../sw/device/lib/dif/dif_plic_unittest.cc: In member function ‘virtual void dif_plic_unittest::{anonymous}::IrqCompleteTest_NullArgs_Test::TestBody()’:
../sw/device/lib/dif/dif_plic_unittest.cc:345:34: error: ‘data’ may be used uninitialized [-Werror=maybe-uninitialized]
  345 |   EXPECT_EQ(dif_plic_irq_complete(nullptr, kTarget0, &data), kDifPlicBadArg);
      |             ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../sw/device/lib/dif/dif_plic_unittest.cc:5:
/home/philipp/src/opentitan/sw/device/lib/dif/dif_plic.h:295:19: note: by argument 3 of type ‘const dif_plic_irq_id_t*’ {aka ‘const unsigned int*’} to ‘dif_plic_result_t dif_plic_irq_complete(const dif_plic_t*, dif_plic_target_t, const dif_plic_irq_id_t*)’ declared here
  295 | dif_plic_result_t dif_plic_irq_complete(const dif_plic_t *plic,
      |                   ^~~~~~~~~~~~~~~~~~~~~
../sw/device/lib/dif/dif_plic_unittest.cc:344:21: note: ‘data’ declared here
  344 |   dif_plic_irq_id_t data;
      |                     ^~~~
cc1plus: all warnings being treated as errors
```

Signed-off-by: Philipp Wagner <phw@lowrisc.org>